# Generated by Django 5.2.8 on 2025-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotensiEkonomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=200)),
                ('sektor', models.CharField(choices=[('pertanian', 'Pertanian'), ('pariwisata', 'Pariwisata'), ('industri', 'Industri'), ('perdagangan', 'Perdagangan'), ('lainnya', 'Lainnya')], max_length=100)),
                ('estimasi_nilai', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SimtaxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(blank=True, max_length=2, null=True)),
                ('bulan_huruf', models.CharField(blank=True, max_length=20, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('nopd', models.CharField(blank=True, max_length=30, null=True)),
                ('npwpd', models.CharField(blank=True, max_length=20, null=True)),
                ('wp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('objek_id', models.CharField(blank=True, max_length=50, null=True)),
                ('objek_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('objek_alamat', models.TextField(blank=True, null=True)),
                ('pengguna_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('subjenispajak_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subjenispajak_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('omzet_makanan', models.IntegerField(blank=True, null=True)),
                ('omzet_minuman', models.IntegerField(blank=True, null=True)),
                ('pajak', models.IntegerField(blank=True, null=True)),
                ('status_bayar', models.BooleanField(blank=True, null=True)),
                ('tgl_bayar', models.DateField(blank=True, null=True)),
                ('tglbayar1', models.DateTimeField(blank=True, null=True)),
                ('tgl_entry', models.DateTimeField(blank=True, null=True)),
                ('tgl_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('transaksi_jmlhbayardenda', models.IntegerField(blank=True, null=True)),
                ('transaksi_jmlhdendapembayaran', models.IntegerField(blank=True, null=True)),
                ('transaksi_kodebayarbank', models.CharField(blank=True, max_length=50, null=True)),
                ('transaksi_kodeqris', models.TextField(blank=True, null=True)),
                ('transaksi_masaawal', models.DateField(blank=True, null=True)),
                ('transaksi_masaakhir', models.DateField(blank=True, null=True)),
                ('transaksi_periodepajak', models.CharField(blank=True, max_length=4, null=True)),
                ('transaksi_tglawalreklame', models.CharField(blank=True, max_length=20, null=True)),
                ('transaksi_tglakhirreklame', models.CharField(blank=True, max_length=20, null=True)),
                ('transaksi_propertis', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
