# Generated by Django 5.2.8 on 2025-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(max_length=200, unique=True)),
                ('subjenispajak_id', models.CharField(max_length=200)),
                ('subjenispajak_nama', models.CharField(max_length=200)),
                ('target_tahun', models.PositiveIntegerField()),
                ('target_nominal', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
