# Generated by Django 5.2.8 on 2025-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_targetpajak'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotensiBaru',
            fields=[
                ('id_potensi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_potensi', models.CharField(max_length=200)),
                ('deskripsi_potensi', models.TextField(blank=True, null=True)),
                ('perangkat_daerah_pengusul', models.CharField(max_length=150)),
                ('lokasi', models.CharField(blank=True, max_length=150, null=True)),
                ('kategori_sektor', models.CharField(blank=True, max_length=100, null=True)),
                ('status_perda', models.BooleanField(default=False)),
                ('nomor_perda_terkait', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('nilai_estimasi', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('catatan_analisis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Potensi Baru',
                'verbose_name_plural': 'Potensi Baru',
            },
        ),
    ]
